### ISSUE TITLE
Update library to support ST25R95 card emulation mode

### ISSUE THREAD

**Issue by sebastianschuler** [stm32duino/X-NUCLEO-NFC03A1#6]
Will the library be updated to fully support the new ST25R95 card emulation mode?

**Comment by cparata** [comment]
Hi @sebastianschuler ,
unfortunately, it is not foreseen to add card emulation support on this library. Any contribution of the community to add new features at this library like card emulation is welcome.
Best Regards,
Carlo

**Comment by sebastianschuler** [comment]
Okay, thanks! Is there a different library from ST that supports card emulation for the ST25R95?

**Comment by cparata** [comment]
Hi @sebastianschuler ,
maybe you can give a look at STSW-ST95HF001 software that you can download from st.com [(link)](https://www.st.com/content/st_com/en/products/embedded-software/st25-nfc-rfid-software/stsw-st95hf001.html). The card emulation code is mainly in lib_PICC.c file. Take into account that we officially support for this chip only the Card Emulation for ISO14443A, even if in the code you can find the card emulation also for ISO14443B and Felica. STSW-ST95HF001 has also proprietary P2P stuff that should not  be ported as well. I hope that it could be useful for you.
Best Regards,
Carlo

**Comment by fpistm** [comment]
OP is a question and it was answered.
No internal plan to update it.
Any contribution are welcome 😉
